### ISSUE TITLE
Crash at attempting to play a videi on 0.16.13

### ISSUE THREAD

**Issue by czarkoff** [lbryio/lbry-fdroid#10]
### Steps to reproduce
1.  Tap any video

### Expected behaviour
Video is played

### Actual behaviour
Application crashes.

## System Configuration
- Device: Xiaomi Redmi Note 8 Pro
- Android version: Android 10

## Anything Else

Trace

> java.lang.SecurityException: Neither user 10399 nor current process has android.permission.WAKE_LOCK.
> at android.os.Parcel.createException(Parcel.java:2074)
> 	at android.os.Parcel.readException(Parcel.java:2042)
> 	at android.os.Parcel.readException(Parcel.java:1990)
> 	at android.os.IPowerManager$Stub$Proxy.acquireWakeLock(IPowerManager.java:750)
> 	at android.os.PowerManager$WakeLock.acquireLocked(PowerManager.java:2188)
> 	at android.os.PowerManager$WakeLock.acquire(PowerManager.java:2154)
> 	at com.google.android.exoplayer2.WakeLockManager.updateWakeLock(WakeLockManager.java:96)
> 	at com.google.android.exoplayer2.WakeLockManager.setStayAwake(WakeLockManager.java:83)
> 	at com.google.android.exoplayer2.SimpleExoPlayer.updateWakeAndWifiLock(SimpleExoPlayer.java:2077)
> 	at com.google.android.exoplayer2.SimpleExoPlayer.access$4700(SimpleExoPlayer.java:75)
> 	at com.google.android.exoplayer2.SimpleExoPlayer$ComponentListener.onPlaybackStateChanged(SimpleExoPlayer.java:2407)
> 	at com.google.android.exoplayer2.ExoPlayerImpl$PlaybackInfoUpdate.lambda$run$7$ExoPlayerImpl$PlaybackInfoUpdate(ExoPlayerImpl.java:1447)
> 	at com.google.android.exoplayer2.-$$Lambda$ExoPlayerImpl$PlaybackInfoUpdate$tUn7tXLH0gigHS24TehPEnTXTJ0.invokeListener(Unknown Source:2)
> 	at com.google.android.exoplayer2.BasePlayer$ListenerHolder.invoke(BasePlayer.java:279)
> 	at com.google.android.exoplayer2.ExoPlayerImpl.invokeAll(ExoPlayerImpl.java:1496)
> 	at com.google.android.exoplayer2.ExoPlayerImpl.access$100(ExoPlayerImpl.java:56)
> 	at com.google.android.exoplayer2.ExoPlayerImpl$PlaybackInfoUpdate.run(ExoPlayerImpl.java:1445)
> 	at com.google.android.exoplayer2.ExoPlayerImpl.notifyListeners(ExoPlayerImpl.java:1326)
> 	at com.google.android.exoplayer2.ExoPlayerImpl.updatePlaybackInfo(ExoPlayerImpl.java:954)
> 	at com.google.android.exoplayer2.ExoPlayerImpl.prepare(ExoPlayerImpl.java:320)
> 	at com.google.android.exoplayer2.SimpleExoPlayer.prepare(SimpleExoPlayer.java:1402)
> 	at com.google.android.exoplayer2.SimpleExoPlayer.prepare(SimpleExoPlayer.java:1427)
> 	at io.lbry.browser.ui.findcontent.FileViewFragment.playMedia(FileViewFragment.java:1729)
> 	at io.lbry.browser.ui.findcontent.FileViewFragment.handleMainActionForClaim(FileViewFragment.java:1951)
> 	at io.lbry.browser.ui.findcontent.FileViewFragment.onMainActionButtonClicked(FileViewFragment.java:1840)
> 	at io.lbry.browser.ui.findcontent.FileViewFragment.renderClaim(FileViewFragment.java:1597)
> 	at io.lbry.browser.ui.findcontent.FileViewFragment.checkParams(FileViewFragment.java:459)
> 	at io.lbry.browser.ui.findcontent.FileViewFragment.onResume(FileViewFragment.java:706)
> 	at androidx.fragment.app.Fragment.performResume(Fragment.java:2747)
> 	at androidx.fragment.app.FragmentStateManager.resume(FragmentStateManager.java:373)
> 	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1199)
> 	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1356)
> 	at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1434)
> 	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1497)
> 	at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:447)
> 	at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2169)
> 	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1992)
> 	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1947)
> 	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1849)
> 	at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:413)
> 	at android.os.Handler.handleCallback(Handler.java:914)
> 	at android.os.Handler.dispatchMessage(Handler.java:100)
> 	at android.os.Looper.loop(Looper.java:224)
> 	at android.app.ActivityThread.main(ActivityThread.java:7551)
> 	at java.lang.reflect.Method.invoke(Native Method)
> 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
> 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995)
> Caused by: android.os.RemoteException: Remote stack trace:
> 	at android.app.ContextImpl.enforce(ContextImpl.java:1907)
> 	at android.app.ContextImpl.enforceCallingOrSelfPermission(ContextImpl.java:1935)
> 	at com.android.server.power.PowerManagerService$BinderService.acquireWakeLock(PowerManagerService.java:4427)
> 	at android.os.IPowerManager$Stub.onTransact(IPowerManager.java:350)
> 	at android.os.Binder.execTransactInternal(Binder.java:1021)

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by kekkyojin** [comment]
This is going to be fixed on 0.16.14a or next release. Unfortunately, 0.16.14 was already built by FDroid servers when this issue was noticed, so the fix is not going to get there.

Sorry for the inconvenience. A fixed release will land in a few days, depending on FDroid build servers.

**Comment by llewlem888** [comment]
I've got this problem also. It's infuriating that I can't watch Jeremy's latest vids on his own platform. Pls never again.

**Comment by viceverser** [comment]
Why don't you have a more current apk available for download direct? Still waiting to try this broken app.

**Comment by kekkyojin** [comment]
FDroid signes every release with a digital signature created for every app. They own the key to sign the release, not LBRY, @viceverser

**Comment by viceverser** [comment]
I don't understand... I can direct download other apps as an apk, that get direct push in app updates, why is LBRY such an exception? Surely there is no need for f-droid to play middle man? Especially if they are this incapable of keeping up with the actual project? And if big tech has taught us anything this year, it's that any vendor we use can be targeted to attack any competition of the tech monopolies... How long you think before f-droid is slandered in the media to remove apps that are a threat to the oligopoly? I'm just saying, if there is an option to directly release to your audience, why not give the option?

**Comment by kekkyojin** [comment]
Fixed on now released 0.16.15 version
