### ISSUE TITLE
App crashes (update 0.16.13)

### ISSUE THREAD

**Issue by ksapp-dell** [lbryio/lbry-fdroid#11]
## The Issue
The latest version crashes immediately when you start a video.  The audio keeps playing without video and Android shows a crash notification window. I deleted all app data first and then deleted the app an installed it again. This did not help. I downgraded to the version before and now it is working ok.
### Steps to reproduce
1.open  a video
2.
3.

### Expected behaviour
Tell us what should happen
No crash
### Actual behaviour
Tell us what happens instead
Crash

## System Configuration
- Device: Samsung S7
- Android version: 8.0
- original- no root or anything like this.
### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by akinwale** [comment]
Issue transfer done.

**Comment by kekkyojin** [comment]
Thanks, @akinwale .

Version 0.16.14 still shows the problem, @ksapp-dell . It will be fixed on next LBRY update. To fix it as quick as possible, I created a PR for 0.16.14a, which is the one with the fix applied. It has still to be merged.

**Comment by kekkyojin** [comment]
Fixed on now released 0.16.15 version
