### ISSUE TITLE
Screenshots for F-Droid

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [lbryio/lbry-fdroid#8]
You can add Screenshots for F-Droid, too, if you want. https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/ https://gitlab.com/snippets/1895688 That was simply information about what is still possible. You would then only have to enter the screenshots in fastlane.

**Comment by kauffj** [comment]
@kekkyojin can you add these? You can take the pictures from https://play.google.com/store/apps/details

**Comment by mondlicht-und-sterne** [comment]
If you can do that, that would be very nice

and otherwise or after, then close the issue. thank you

**Comment by kekkyojin** [comment]
Sure, @kauffj

**Comment by kauffj** [comment]
thanks @kekkyojin!
